name: Deploy Voice Recorder Backend

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          cd backendServerless
          npm install

      # Step 4: Create Lambda Layer for uuid
      - name: Create Lambda Layer for uuid
        run: |
          mkdir -p my-layer/nodejs
          npm install uuid --prefix ./my-layer/nodejs
          cd my-layer
          zip -r layer.zip nodejs

      # Step 5: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 6: Publish Lambda Layer
      - name: Publish Lambda Layer
        run: |
          LAYER_ARN=$(aws lambda publish-layer-version \
            --layer-name uuid-layer \
            --zip-file fileb://my-layer/layer.zip \
            --compatible-runtimes nodejs18.x \
            --query 'LayerVersionArn' --output text \
            --region ap-south-1)
          echo "Layer ARN: $LAYER_ARN"
          echo "LAYER_ARN=$LAYER_ARN" >> $GITHUB_ENV

      # Step 7: Package Lambda function
      - name: Package Lambda function
        run: |
          cd backendServerless
          zip -r lambda.zip .

      # Step 8: Deploy Lambda function
      - name: Deploy Lambda function
        run: |
          FUNCTION_EXISTS=$(aws lambda get-function --function-name VoiceRecorderFunction --query 'Configuration.FunctionName' --output text || echo "NOT_FOUND")

          if [ "$FUNCTION_EXISTS" = "NOT_FOUND" ]; then
            echo "Creating Lambda function..."
            aws lambda create-function \
              --function-name VoiceRecorderFunction \
              --runtime nodejs18.x \
              --role arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_LAMBDA_ROLE }} \
              --handler index.handler \
              --zip-file fileb://backendServerless/lambda.zip \
              --timeout 6 \
              --memory-size 512 \
              --region ap-south-1
          else
            echo "Updating Lambda function code..."
            aws lambda update-function-code \
              --function-name VoiceRecorderFunction \
              --zip-file fileb://backendServerless/lambda.zip \
              --region ap-south-1

            echo "Updating Lambda function configuration..."
            while true; do
              UPDATE_STATUS=$(aws lambda get-function-configuration --function-name VoiceRecorderFunction --query 'State' --output text)
              if [ "$UPDATE_STATUS" = "Active" ]; then
                aws lambda update-function-configuration \
                  --function-name VoiceRecorderFunction \
                  --timeout 6 \
                  --memory-size 512 \
                  --layers ${{ env.LAYER_ARN }} \
                  --region ap-south-1
                break
              else
                echo "Lambda function is still being updated, retrying in 10 seconds..."
                sleep 10
              fi
            done
          fi

      # Step 9: Set up API Gateway
      - name: Set up API Gateway
        run: |
          REST_API_ID=$(aws apigateway get-rest-apis --query "items[?name=='VoiceRecorderAPI'].id" --output text --region ap-south-1)

          if [ -z "$REST_API_ID" ]; then
            echo "Creating new API Gateway..."
            REST_API_ID=$(aws apigateway create-rest-api --name "VoiceRecorderAPI" --query 'id' --output text --region ap-south-1)
          else
            echo "Using existing API Gateway: $REST_API_ID"
          fi

          ROOT_RESOURCE_ID=$(aws apigateway get-resources --rest-api-id $REST_API_ID --query 'items[0].id' --output text --region ap-south-1)

          AUDIO_RESOURCE_ID=$(aws apigateway create-resource \
            --rest-api-id $REST_API_ID \
            --parent-id $ROOT_RESOURCE_ID \
            --path-part audio --query 'id' --output text --region ap-south-1 || \
            aws apigateway get-resources \
              --rest-api-id $REST_API_ID \
              --query "items[?path=='/audio'].id" --output text --region ap-south-1)

          create_endpoint() {
            ENDPOINT=$1
            RESOURCE_ID=$(aws apigateway create-resource \
              --rest-api-id $REST_API_ID \
              --parent-id $AUDIO_RESOURCE_ID \
              --path-part $ENDPOINT \
              --query 'id' --output text --region ap-south-1 || \
              aws apigateway get-resources \
                --rest-api-id $REST_API_ID \
                --query "items[?path=='/audio/$ENDPOINT'].id" --output text --region ap-south-1)

            aws apigateway put-method \
              --rest-api-id $REST_API_ID \
              --resource-id $RESOURCE_ID \
              --http-method POST \
              --authorization-type "NONE" \
              --region ap-south-1

            aws apigateway put-integration \
              --rest-api-id $REST_API_ID \
              --resource-id $RESOURCE_ID \
              --http-method POST \
              --type AWS_PROXY \
              --integration-http-method POST \
              --uri "arn:aws:apigateway:ap-south-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-south-1:${{ secrets.AWS_ACCOUNT_ID }}:function:VoiceRecorderFunction/invocations" \
              --region ap-south-1
          }

          create_endpoint "add"
          create_endpoint "list"
          create_endpoint "merge"
          create_endpoint "remove"

          aws apigateway create-deployment \
            --rest-api-id $REST_API_ID \
            --stage-name dev \
            --region ap-south-1

          echo "API Gateway endpoint: https://${REST_API_ID}.execute-api.ap-south-1.amazonaws.com/dev/audio/"
