name: Deploy to AWS Lambda

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Dependencies
        run: npm install

      - name: Package Lambda Function
        run: |
          mkdir -p deployment_package
          cp -r src node_modules package.json package-lock.json deployment_package/
          cd deployment_package
          zip -r ../lambda_function.zip .
          cd ..

      - name: Deploy Lambda Functions
        run: |
          aws lambda create-function \
            --function-name AddAudio \
            --runtime nodejs18.x \
            --role arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_LAMBDA_ROLE }} \
            --handler src/app.addAudio \
            --zip-file fileb://lambda_function.zip || \
          aws lambda update-function-code \
            --function-name AddAudio \
            --zip-file fileb://lambda_function.zip

          aws lambda create-function \
            --function-name MergeAudio \
            --runtime nodejs18.x \
            --role arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_LAMBDA_ROLE }} \
            --handler src/app.mergeAudio \
            --zip-file fileb://lambda_function.zip || \
          aws lambda update-function-code \
            --function-name MergeAudio \
            --zip-file fileb://lambda_function.zip

          aws lambda create-function \
            --function-name ListAudio \
            --runtime nodejs18.x \
            --role arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_LAMBDA_ROLE }} \
            --handler src/app.listAudio \
            --zip-file fileb://lambda_function.zip || \
          aws lambda update-function-code \
            --function-name ListAudio \
            --zip-file fileb://lambda_function.zip

      - name: Create API Gateway
        run: |
          api_gateway_id=$(aws apigateway create-rest-api --name "VoiceRecorderAPI" --query 'id' --output text)

          root_resource_id=$(aws apigateway get-resources --rest-api-id $api_gateway_id --query 'items[0].id' --output text)

          aws apigateway put-method \
            --rest-api-id $api_gateway_id \
            --resource-id $root_resource_id \
            --http-method POST \
            --authorization-type "NONE"

          aws apigateway put-integration \
            --rest-api-id $api_gateway_id \
            --resource-id $root_resource_id \
            --http-method POST \
            --type AWS_PROXY \
            --uri "arn:aws:apigateway:${{ secrets.AWS_REGION }}:lambda:path/2015-03-31/functions/arn:aws:lambda:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:function:AddAudio/invocations"

          aws apigateway create-deployment \
            --rest-api-id $api_gateway_id \
            --stage-name qa

          echo "API Gateway URL: https://${api_gateway_id}.execute-api.${{ secrets.AWS_REGION }}.amazonaws.com/qa"

      - name: Add Permissions to Lambda
        run: |
          aws lambda add-permission \
            --function-name AddAudio \
            --statement-id apigateway-post \
            --action lambda:InvokeFunction \
            --principal apigateway.amazonaws.com \
            --source-arn "arn:aws:execute-api:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:${api_gateway_id}/*/POST/"

          aws lambda add-permission \
            --function-name MergeAudio \
            --statement-id apigateway-post \
            --action lambda:InvokeFunction \
            --principal apigateway.amazonaws.com \
            --source-arn "arn:aws:execute-api:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:${api_gateway_id}/*/POST/"

          aws lambda add-permission \
            --function-name ListAudio \
            --statement-id apigateway-get \
            --action lambda:InvokeFunction \
            --principal apigateway.amazonaws.com \
            --source-arn "arn:aws:execute-api:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:${api_gateway_id}/*/GET/"
