name: Deploy to AWS Lambda

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install Dependencies
        working-directory: backend
        run: npm install

      - name: Package Lambda Function
        working-directory: backend
        run: |
          zip -r ../lambda_function.zip .

      - name: Deploy Lambda Function
        run: |
          if aws lambda get-function --function-name VoiceRecorderAPI; then
            aws lambda update-function-code \
              --function-name VoiceRecorderAPI \
              --zip-file fileb://lambda_function.zip
          else
            aws lambda create-function \
              --function-name VoiceRecorderAPI \
              --runtime nodejs18.x \
              --role arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_LAMBDA_ROLE }} \
              --handler src/index.handler \
              --zip-file fileb://lambda_function.zip
          fi

      - name: Create API Gateway and Integrate with Lambda
        run: |
          api_gateway_id=$(aws apigateway create-rest-api --name "VoiceRecorderAPI" --query 'id' --output text)

          root_resource_id=$(aws apigateway get-resources --rest-api-id $api_gateway_id --query 'items[0].id' --output text)

          # Add routes
          for endpoint in add merge list; do
            resource_id=$(aws apigateway create-resource \
              --rest-api-id $api_gateway_id \
              --parent-id $root_resource_id \
              --path-part audio/$endpoint \
              --query 'id' --output text)

            aws apigateway put-method \
              --rest-api-id $api_gateway_id \
              --resource-id $resource_id \
              --http-method POST \
              --authorization-type "NONE"

            aws apigateway put-integration \
              --rest-api-id $api_gateway_id \
              --resource-id $resource_id \
              --http-method POST \
              --type AWS_PROXY \
              --uri "arn:aws:apigateway:${{ secrets.AWS_REGION }}:lambda:path/2015-03-31/functions/arn:aws:lambda:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:function:VoiceRecorderAPI/invocations"
          done

          # Deploy the API
          aws apigateway create-deployment \
            --rest-api-id $api_gateway_id \
            --stage-name qa

          echo "API Gateway URL: https://${api_gateway_id}.execute-api.${{ secrets.AWS_REGION }}.amazonaws.com/qa"

      - name: Add Permissions to Lambda
        run: |
          aws lambda add-permission \
            --function-name VoiceRecorderAPI \
            --statement-id apigateway-invoke \
            --action lambda:InvokeFunction \
            --principal apigateway.amazonaws.com \
            --source-arn "arn:aws:execute-api:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:${api_gateway_id}/*"
